### ISSUE TITLE
Binary Tree Algorithm seems to be not working

### ISSUE THREAD

**Issue by dpsutton** [amacdougall/mazes#2]
Hi.

I'm using your repo here to work through the maze book and it is incredibly nice. I swapped in the binary tree algorithm and I'm not getting good results. The maze should be a perfect maze, ie, every cell has a path to every other cell. However, this is not the results I am getting:

![image](https://cloud.githubusercontent.com/assets/6377293/19890477/ed9d73e8-a008-11e6-939a-d18b6604a6d9.png)

My suspicion is that this is a disparity in the renderer compared to how the data is organized but I'm not sure. But I'm gonna this down and wanted to highlight that it may not be faithfully representing the data structures.

**Comment by amacdougall** [comment]
Okay, so I noticed this issue seven years later, sorry. This is a renderer thing. I chose to render the maze as a grid of cells, with lines showing the paths between them. Inspired by the text-adventure maps I used to make as a kid. So you're looking at a 4x4 grid. The whitespace between cells is purely cosmetic.

This image should make it more clear what's going on.

<img width="385" alt="Screenshot 2023-04-08 at 10 37 25 AM" src="https://user-images.githubusercontent.com/592916/230727071-531a8c7b-0c3b-477b-be9c-1f28a07f4005.png">
